<a href="https://colab.research.google.com/github/vanshikaamahajan/Tweet-search/blob/main/Tweet_search.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Install Package**

In [1]:
!pip install tweepy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: tweepy in /usr/local/lib/python3.10/dist-packages (4.13.0)
Requirement already satisfied: oauthlib<4,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from tweepy) (3.2.2)
Requirement already satisfied: requests<3,>=2.27.0 in /usr/local/lib/python3.10/dist-packages (from tweepy) (2.27.1)
Requirement already satisfied: requests-oauthlib<2,>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from tweepy) (1.3.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27.0->tweepy) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27.0->tweepy) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27.0->tweepy) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27.0->tweepy) (3.4)

**Add Credentials**

In [2]:
access_token = "501682241-ZG1DshytyxUIUY8FXPoH2AXaDG9d5DQlORemfAzU"
access_token_secret = "mxwCYkDjgWG5qWy8ONtVs3j2lxiYSxyberVVa92jmd27z"
consumer_key = "we0Drpnvc1FZNazKkiKoFWlGf"
consumer_secret = "OXRvmJwM6ca9k90XMIMoktSCa5XvjNieqJivcfjbOAlmpO6RhH"

In [3]:
import os
import tweepy as tw
import pandas as pd

In [4]:
auth = tw.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tw.API(auth, wait_on_rate_limit=True)

*Look for tweets and build a dataframe*

In [8]:
# Collect tweets
results = api.search_tweets(q='covid', count=100)

# We create a pandas dataframe as follows:
data = pd.DataFrame(data=[tweet.text for tweet in results], columns=['Tweets'])

# We display the first 10 elements of the dataframe:
display(data.head(10))

                                              Tweets
0  RT @toobaffled: I don’t think this is normal. ...
1  RT @TheChiefNerd: July 2021: "Unvaccinated Ame...
2  RT @zerohedge: 10% Of $4.2 Trillion US COVID R...
3  RT @davidicke: What absolute bollocks – clearl...
4  RT @HarrySpoelstra: Natural history of #LongCo...
5  @Adisabadan @zagey_yya @YeleSowore Were you ou...
6  @NJDavidD can we also talk about the hotels th...
7  RT @TheChiefNerd: July 2021: "Unvaccinated Ame...
8  @st_hennermann @Zero_Long_Covid @BioNTech_Grou...
9  RT @MacroMicroMe: 🇨🇳China's Containerized Frei...

In [6]:
data

                                               Tweets
0   RT @DineshC1999: Retweet fastly➕ follow All wh...
1   RT @ravi3383: *WORLD BLOOD DONORS DAY:ROORKEE ...
2   @ravi3383 @HQ_DG_NCC @drajaykumar_ias @WHO Wel...
3   The handsets are offered in three different co...
4   What are the options for a UI/UX Designer cour...
..                                                ...
87  @sumiiithh @Vanshika_46 Hein?this is new to me...
88                                     @Vanshika_46 😅
89  @Vanshika_46 whi to jb paper hi 716 ka hogya t...
90  Bhai 720/720 kaise la sakte hai bacche neet me...
91                             “Vanshika bhagwan hai”

[92 rows x 1 columns]

Find more at [Tweet Extraction](https://github.com/RodolfoFerro/pandas_twitter/blob/master/01-extracting-data.md)

In [7]:
data

                                               Tweets
0   RT @DineshC1999: Retweet fastly➕ follow All wh...
1   RT @ravi3383: *WORLD BLOOD DONORS DAY:ROORKEE ...
2   @ravi3383 @HQ_DG_NCC @drajaykumar_ias @WHO Wel...
3   The handsets are offered in three different co...
4   What are the options for a UI/UX Designer cour...
..                                                ...
87  @sumiiithh @Vanshika_46 Hein?this is new to me...
88                                     @Vanshika_46 😅
89  @Vanshika_46 whi to jb paper hi 716 ka hogya t...
90  Bhai 720/720 kaise la sakte hai bacche neet me...
91                             “Vanshika bhagwan hai”

[92 rows x 1 columns]